### PR TITLE
Turn on links and options for guests

### PR DESCRIPTION
**Pull request by vinny**
dont need `S_IS_BOT` and `S_USER_LOGGED_IN`, permissions can do this job.

### CODE REVIEW

**Comment by dmzx** [comment]
Do we want to use the permission to view the items?

$this->auth->acl_get('u_video_view')

**Comment by vinny** [comment]
I honestly think it is not necessary. 

We will leave the link free of permissions, the rest of the pages are already defined by permissions.

**Comment by dmzx** [comment]
So like its now the guests can always see the uploaded videos on index??
And when they click on video the will be blocked by auth.

**Comment by vinny** [comment]
I forgot that.
Maybe add a condition, just link `<!-- IF S_CAN_VIEW_GALLERY -->` instead of `S_IS_BOT` and `S_USER_LOGGED_IN`.

We can use the in link and the latest videos block. What you think?

**Comment by dmzx** [comment]
Yes can do `<!-- IF S_CAN_VIEW_GALLERY -->`  
You want to do it with `$this->auth->acl_get('u_video_view')`  ?

**Comment by vinny** [comment]
`u_video_view_full` to see the link.

`u_video_view` to see latest videos block.

**Comment by dmzx** [comment]
Ok will add it :)

**Comment by dmzx** [comment]
https://github.com/dmzx/youtubegallery/commit/e6a1d4dacdb4138cb9566ca0c7e331a2201ff528

**Comment by vinny** [comment]
Nice. 👍

**Pull request merged**
